names:
  0: A400M
  1: An124
  2: An22
  3: An225
  4: An72
  5: C1
  6: C130
  7: C17
  8: C2
  9: C390
  10: C5
  11: Il76
  12: Y20
nc: 13
path: yolo_specialist_datasets/cargo
train: images/train
val: images/val
